import test from "node:test";
import assert from "node:assert/strict";
import { determineActivityState, detectClearCommand } from "../activity-monitor.js";

// ── assistant + stop_reason variants ────────────────────────────────────────

test("assistant with stop_reason null → running", () => {
  assert.equal(
    determineActivityState({
      type: "assistant",
      message: { stop_reason: null, content: [{ type: "thinking" }] },
    }),
    "running",
  );
});

test("assistant with text content and stop_reason undefined → completed", () => {
  assert.equal(
    determineActivityState({
      type: "assistant",
      message: { content: [{ type: "text" }] },
    }),
    "completed",
  );
});

test("assistant with thinking content and stop_reason undefined → running", () => {
  assert.equal(
    determineActivityState({
      type: "assistant",
      message: { content: [{ type: "thinking" }] },
    }),
    "running",
  );
});

test("assistant with tool_use content and stop_reason undefined → pending", () => {
  assert.equal(
    determineActivityState({
      type: "assistant",
      message: { content: [{ type: "tool_use" }] },
    }),
    "pending",
  );
});

test("assistant with no message field → running", () => {
  assert.equal(
    determineActivityState({ type: "assistant" }),
    "running",
  );
});

test("assistant with stop_reason tool_use → pending", () => {
  assert.equal(
    determineActivityState({
      type: "assistant",
      message: { stop_reason: "tool_use", content: [{ type: "tool_use" }] },
    }),
    "pending",
  );
});

test("assistant with stop_reason end_turn → completed", () => {
  assert.equal(
    determineActivityState({
      type: "assistant",
      message: { stop_reason: "end_turn", content: [{ type: "text" }] },
    }),
    "completed",
  );
});

test("assistant with stop_reason stop_sequence → completed", () => {
  assert.equal(
    determineActivityState({
      type: "assistant",
      message: { stop_reason: "stop_sequence", content: [{ type: "text" }] },
    }),
    "completed",
  );
});

test("assistant with stop_reason max_tokens → completed", () => {
  assert.equal(
    determineActivityState({
      type: "assistant",
      message: { stop_reason: "max_tokens", content: [{ type: "text" }] },
    }),
    "completed",
  );
});

// ── user entries ────────────────────────────────────────────────────────────

test("user with text content → running", () => {
  assert.equal(
    determineActivityState({
      type: "user",
      message: { content: [{ type: "text", text: "hello" }] },
    }),
    "running",
  );
});

test("user with tool_result → running", () => {
  assert.equal(
    determineActivityState({
      type: "user",
      message: { content: [{ type: "tool_result" }] },
    }),
    "running",
  );
});

// ── progress entries ────────────────────────────────────────────────────────

test("progress entry with PreToolUse hook → running", () => {
  assert.equal(
    determineActivityState({
      type: "progress",
      data: { type: "hook_progress", hookEvent: "PreToolUse" },
    }),
    "running",
  );
});

test("progress entry with Stop hook → completed", () => {
  assert.equal(
    determineActivityState({
      type: "progress",
      data: { type: "hook_progress", hookEvent: "Stop" },
    }),
    "completed",
  );
});

test("progress entry without hookEvent → running", () => {
  assert.equal(
    determineActivityState({
      type: "progress",
      data: { type: "hook_progress" },
    }),
    "running",
  );
});

// ── unknown type ────────────────────────────────────────────────────────────

test("unknown type falls back to idle", () => {
  assert.equal(
    determineActivityState({ type: "unknown" }),
    "idle",
  );
});

// ── local command entries (user type) ───────────────────────────────────────

test("user with <command-name> → completed", () => {
  assert.equal(
    determineActivityState({
      type: "user",
      message: {
        role: "user",
        content:
          '<command-name>/mcp</command-name>\n            <command-message>mcp</command-message>\n            <command-args></command-args>',
      },
    }),
    "completed",
  );
});

test("user with <local-command-stdout> → completed", () => {
  assert.equal(
    determineActivityState({
      type: "user",
      message: {
        role: "user",
        content: "<local-command-stdout>No MCP servers configured.</local-command-stdout>",
      },
    }),
    "completed",
  );
});

test("user with <local-command-caveat> → completed", () => {
  assert.equal(
    determineActivityState({
      type: "user",
      message: {
        role: "user",
        content:
          "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>",
      },
    }),
    "completed",
  );
});

test("user with array content containing <command-name> → completed", () => {
  assert.equal(
    determineActivityState({
      type: "user",
      message: {
        role: "user",
        content: [{ type: "text", text: "<command-name>/status</command-name>" }],
      },
    }),
    "completed",
  );
});

test("user with plain text (no command tags) → running", () => {
  assert.equal(
    determineActivityState({
      type: "user",
      message: { role: "user", content: "hello world" },
    }),
    "running",
  );
});

// ── system + local_command entries ──────────────────────────────────────────

test("system with subtype local_command → completed", () => {
  assert.equal(
    determineActivityState({
      type: "system",
      subtype: "local_command",
      content: "<local-command-stdout>Status dialog dismissed</local-command-stdout>",
    }),
    "completed",
  );
});

test("system without subtype → idle", () => {
  assert.equal(
    determineActivityState({ type: "system" }),
    "idle",
  );
});

test("system with other subtype → idle", () => {
  assert.equal(
    determineActivityState({ type: "system", subtype: "info" }),
    "idle",
  );
});

// ── detectClearCommand ──────────────────────────────────────────────────────

test("detectClearCommand: string content with /clear → true", () => {
  assert.equal(
    detectClearCommand({
      type: "user",
      message: {
        role: "user",
        content:
          '<command-name>/clear</command-name>\n            <command-message>clear</command-message>\n            <command-args></command-args>',
      },
    }),
    true,
  );
});

test("detectClearCommand: array content with /clear → true", () => {
  assert.equal(
    detectClearCommand({
      type: "user",
      message: {
        role: "user",
        content: [{ type: "text", text: "<command-name>/clear</command-name>" }],
      },
    }),
    true,
  );
});

test("detectClearCommand: plain user message → false", () => {
  assert.equal(
    detectClearCommand({
      type: "user",
      message: { role: "user", content: "please clear the screen" },
    }),
    false,
  );
});

test("detectClearCommand: other command (/mcp) → false", () => {
  assert.equal(
    detectClearCommand({
      type: "user",
      message: {
        role: "user",
        content: "<command-name>/mcp</command-name>",
      },
    }),
    false,
  );
});

test("detectClearCommand: non-user type → false", () => {
  assert.equal(
    detectClearCommand({
      type: "assistant",
      message: { content: "<command-name>/clear</command-name>" },
    }),
    false,
  );
});
